// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cheerio = require("cheerio");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var PromiseMonad = require("bs-promise-monad/src/PromiseMonad.bs.js");
var Cheerio$BsCheerio = require("bs-cheerio/src/Cheerio.bs.js");

((require('isomorphic-fetch')));

var releses_url = "https://github.com/VSCodium/vscodium/releases";

PromiseMonad.$great$great$neg(PromiseMonad.$great$great$neg(PromiseMonad.$great$great$neg(PromiseMonad.$great$great$eq(fetch(releses_url), (function (prim) {
                    return prim.text();
                  })), (function (html) {
                return Cheerio$BsCheerio.select(Cheerio.load(html), ".d-flex.flex-items-center.min-width-0[href$=\"amd64.deb\"]").attr("href");
              })), (function (href) {
            return "https://github.com".concat(Belt_Option.getExn((href == null) ? undefined : Caml_option.some(href)));
          })), (function (prim) {
        console.log(prim);
        
      }));

exports.releses_url = releses_url;
/*  Not a pure module */
